spring:
  application:
    #服务名
    name: service-account
  datasource:
    url: jdbc:mysql://188.131.238.102:3306/butterfly?serverTimezone=Asia/Shanghai
    username: root
    password: clearlove321
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.6.3
server:
  #服务端口
  port: 8004

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    #eureka主机名，会在控制页面中显示
    hostname: localhost
    #eureka服务器页面中status的请求路径
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/
