spring:
  application:
    #服务名
    name: service-ui
  resources:
    static-locations: classpath:/static/
server:
  #服务端口
  port: 8000
proxy:
  # localhost:8000/server/example
  servlet_url: /server/*
  # localhost:9000/example
  target_url: http://localhost:9000/
eureka:
  instance:
    #eureka主机名，会在控制页面中显示
    hostname: localhost
    #eureka服务器页面中status的请求路径
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/