spring:
  application:
    #服务名
    name: service-hdfs

server:
  #服务端口
  port: 8003

eureka:
  instance:
    #eureka主机名，会在控制页面中显示
    hostname: localhost
    #eureka服务器页面中status的请求路径
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/

hdfs:
  path: hdfs://node1:9000