spring:
  datasource:
    url: jdbc:mysql://188.131.238.102:3306/butterfly?serverTimezone=Asia/Shanghai
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true