spring:
  application:
    #服务名
    name: service-hbase

server:
  #服务端口
  port: 8002

eureka:
  instance:
    #eureka主机名，会在控制页面中显示
    hostname: localhost
    #eureka服务器页面中status的请求路径
    status-page-url: http://${eureka.instance.hostname}:${server.port}/index
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/

hbase:
  zookeeper:
    quorum: node1,node2,node3
    property:
      clientPort: 2181