spring:
  application:
    #服务名
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: elasticsearch
        uri: lb://service-elasticsearch
        predicates:
        - Path=/es/**
        filters:
        # 关键在下面一句，值为true则开启认证，false则不开启
        # 这种配置方式和spring cloud gateway内置的GatewayFilterFactory一致
        - Authorize=true
      - id: hbase
        uri: lb://service-hbase
        predicates:
        - Path=/hbase/**
        filters:
        # 关键在下面一句，值为true则开启认证，false则不开启
        # 这种配置方式和spring cloud gateway内置的GatewayFilterFactory一致
        - Authorize=true
      - id: hdfs
        uri: lb://service-hdfs
        predicates:
        - Path=/hdfs/**
        filters:
        # 关键在下面一句，值为true则开启认证，false则不开启
        # 这种配置方式和spring cloud gateway内置的GatewayFilterFactory一致
        - Authorize=true
      - id: user
        uri: lb://service-account
        predicates:
        - Path=/user/**
        filters:
        # 关键在下面一句，值为true则开启认证，false则不开启
        # 这种配置方式和spring cloud gateway内置的GatewayFilterFactory一致
        - Authorize=true
      - id: account
        uri: lb://service-account
        predicates:
        - Path=/fake/**,/geographic/**,/account/**
  redis:
    host: 192.168.6.3

server:
  #服务端口
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/