spring:
  application:
    #服务名
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: es
        uri: lb://service-elasticsearch
        predicates:
        - Path=/es/**
      - id: hbase
        uri: lb://service-hbase
        predicates:
        - Path=/hbase/**
      - id: hdfs
        uri: lb://service-hdfs
        predicates:
        - Path=/hdfs/**
      - id: user
        uri: lb://service-user
        predicates:
        - Path=/user/**,/fake/**,/geographic/**,/notice/**

server:
  #服务端口
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #在注册中心中进行注册
      defaultZone: http://localhost:8888/eureka/